version: "3.1"
services:
   db:
      image: postgres:13
      environment:
         POSTGRES_PASSWORD: spring
         POSTGRES_USER: spring
         POSTGRES_DB: proyecto

   backend:
      build: .
      restart: on-failure
      depends_on:
         - db
      ports:
         - 8080:8080